### ISSUE TITLE
Pattern tag in Kirbytext

### ISSUE THREAD

**Issue by illycz** [getkirby-plugins/patterns-plugin#46]
I tried to make tag like snippet explained here: https://forum.getkirby.com/t/embedding-snippets/900/4 but it's not working.

My code:
```
<?php
kirbytext::$tags['pattern'] = array(
  'attr' => array(),
  'html' => function($tag) {
    $file =  $tag->attr('pattern');
    return pattern($file, array(), true);
  }
);
```

I would like to use it in the markdown documetation, which would partly solve this problem: https://github.com/getkirby-plugins/patterns-plugin/issues/5

Thanks

**Comment by illycz** [comment]
I get it: https://getkirby.com/docs/developer-guide/kirbytext/tags

```
<?php
kirbytext::$tags['pattern'] = array(
  'attr' => array(
    'element',
    'class',
    'href',
    'type',
    'label'
  ),
  'html' => function($tag) {
    $file = $tag->attr('pattern');
    $element = $tag->attr('element', 'button');
    $class = $tag->attr('class', '');
    $href = $tag->attr('href', '#');
    $type = $tag->attr('type', 'button');
    $label = $tag->attr('label', 'Button');
    return pattern($file, array('element' => $element, 'class' => $class, 'href' => $href, 'type' => $type, 'label' => $label), true);
  }
);
```
Last question is how to eliminate paragraph wrapping?
Patterns markdown generate pure button but when I use same tag in page textarea, button is wrapped within paragraph.

**Comment by lukasbestle** [comment]
That's probably because a button is considered an "inline" element by the Markdown parser and therefore wrapped.

If you don't want any post-processing (like Markdown or Smartypants parsing), you can instead process your pattern tags in a Kirbytext post-filter:

```php
Kirbytext::$post[] = function($kirbytext, $text) {
  return preg_replace_callback('!(?=[^\]])\(pattern: (.*?)\)!is', function($matches) {
    $pattern = $matches[1];
    
    return pattern($pattern, [], true);
  }, $text);
};
```

This is just a simple example and doesn't support all of your custom attributes, but since post-filters can do any kind of string manipulation, you can extend the filter with support for those.
